version: "3.9"

services:
  serve-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erhan-baran-serve-model
    ports:
      - "5000:5000"

  app:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: erhan-baran-app
    ports:
      - "8501:8501"
    depends_on:
      - serve-model
